var provinces = [
	{"id":"00", "name":"全国", "name_en":"China"},
	{"id":"01", "name":"北京市", "name_en":"Beijing"},
	{"id":"02", "name":"天津市", "name_en":"Tianjin"},
	{"id":"03", "name":"河北省", "name_en":"Hebei"},
	{"id":"04", "name":"山东省", "name_en":"Shandong"},
	{"id":"05", "name":"甘肃省", "name_en":"Gansu"},
	{"id":"06", "name":"新疆维吾尔族自治区", "name_en":"Xinjiang"},
	{"id":"07", "name":"上海市", "name_en":"Shanghai"},
	{"id":"08", "name":"重庆市", "name_en":"Chongqing"},
	{"id":"09", "name":"江苏省", "name_en":"Jiangsu"},
	{"id":"10", "name":"黑龙江省", "name_en":"Heilongjiang"},
	{"id":"11", "name":"贵州省", "name_en":"Guizhou"},
	{"id":"12", "name":"福建省", "name_en":"Fujian"},
	{"id":"13", "name":"河南省", "name_en":"Henan"},
	{"id":"14", "name":"吉林省", "name_en":"Jilin"},
	{"id":"15", "name":"四川省", "name_en":"Sichuan"},
	{"id":"16", "name":"云南省", "name_en":"Yunnan"},
	{"id":"17", "name":"宁夏回族自治区", "name_en":"Ningxia"},
	{"id":"18", "name":"广西壮族自治区", "name_en":"Guangxi"},
	{"id":"19", "name":"台湾省", "name_en":"Taiwan"},
	{"id":"20", "name":"湖南省", "name_en":"Hunan"},
	{"id":"21", "name":"湖北省", "name_en":"Hubei"},
	{"id":"22", "name":"江西省", "name_en":"Jiangxi"},
	{"id":"23", "name":"辽宁省", "name_en":"Liaoning"},
	{"id":"24", "name":"青海省", "name_en":"Qinghai"},
	{"id":"25", "name":"广东省", "name_en":"Guangdong"},
	{"id":"26", "name":"香港特别行政区", "name_en":"Xianggang"},
	{"id":"27", "name":"澳门特别行政区", "name_en":"Aomen"},
	{"id":"28", "name":"陕西省", "name_en":"Shanxi02"},
	{"id":"29", "name":"浙江省", "name_en":"Zhejiang"},
	{"id":"30", "name":"山西省", "name_en":"Shanxi"},
	{"id":"31", "name":"内蒙古自治区", "name_en":"Neimenggu"},
	{"id":"32", "name":"安徽省", "name_en":"Anhui"},
	{"id":"33", "name":"西藏自治区", "name_en":"Xizang"},
	{"id":"34", "name":"海南省", "name_en":"Hainan"}
]
	
var province_cities = {
	"0": [["浙江", "Zhejiang"], ["杭州", "Hangzhou"], ["嘉兴", "Jiaxing"], ["湖州", "Huzhou"], ["绍兴", "Shaoxing"], ["宁波", "Ningbo"], ["舟山", "Zhoushan"], ["衢州", "Quzhou"], ["温州", "Wenzhou"], ["丽水", "Lishui"], ["金华", "Jinhua"], ["台州", "Taizhou"]], 
	"1": [["云南", "Yunnan"], ["昆明", "Kunming"], ["曲靖", "Qujing"], ["玉溪", "Yuxi"], ["保山", "Baoshan"], ["临沧", "Lincang"], ["思茅", "Simao"], ["昭通", "Zhaotong"], ["楚雄", "Chuxiong"], ["怒江", "Nujiang"], ["大理", "Dali"], ["文山", "Wenshan"], ["红河", "Honghe"], ["德宏", "Dehong"], ["迪庆", "Diqing"], ["西双版纳", "Xishuangbanna"]], 
	"2": [["新疆", "Xinjiang"], ["乌鲁木齐", "Wulumuqi"], ["克拉玛依", "Kelamayi"], ["吐鲁番", "Tulufan"], ["喀什", "Kashi"], ["巴音郭楞", "Bayinguoleng"], ["和田", "Hetian"], ["哈密", "Hami"], ["阿勒泰", "Aletai"], ["塔城", "Tacheng"], ["博尔塔", "Boerta"], ["阿克苏", "Akesu"], ["昌吉", "Changji"], ["伊犁", "Yili"], ["克孜勒", "Kezile"]], 
	"3": [["香港", "Xianggang"], ["香港", "Xianggang"]], 
	"4": [["西藏", "Xizang"], ["拉萨", "Lasa"], ["那曲", "Naqu"], ["林芝", "Linzhi"], ["昌都", "Changdu"], ["日喀则", "Rikaze"], ["山南", "Shannan"], ["阿里", "Ali"]], 
	"5": [["台湾", "Taiwan"], ["台湾", "Taiwan"]], 
	"6": [["四川", "Sichuan"], ["成都", "Chengdu"], ["资阳", "Ziyang"], ["乐山", "Leshan"], ["自贡", "Zigong"], ["内江", "Neijiang"], ["眉山", "Meishan"], ["雅安", "Yaan"], ["绵阳", "Mianyang"], ["德阳", "Deyang"], ["遂宁", "Suining"], ["宜宾", "Yibin"], ["南充", "Nanchong"], ["广安", "Guangan"], ["广元", "Guangyuan"], ["巴中", "Bazhong"], ["达州", "Dazhou"], ["攀枝花", "Panzhihua"], ["泸州", "Luzhou"], ["凉山", "Liangshan"], ["阿坝", "Aba"], ["甘孜", "Ganzi"]], 
	"7": [["陕西", "Shaanxi"], ["西安", "Xian"], ["咸阳", "Xianyang"], ["铜川", "Tongchuan"], ["渭南", "Weinan"], ["延安", "Yanan"], ["宝鸡", "Baoji"], ["商洛", "Shangluo"], ["榆林", "Yulin"], ["汉中", "Hanzhong"], ["安康", "Ankang"]], 
	"8": [["山西", "Shanxi"], ["太原", "Taiyuan"], ["晋中", "Jinzhong"], ["临汾", "Linfen"], ["吕梁", "Lvliang"], ["大同", "Datong"], ["阳泉", "Yangquan"], ["朔州", "Shuozhou"], ["忻州", "Xinzhou"], ["长治", "Changzhi"], ["晋城", "Jincheng"], ["运城", "Yuncheng"]], 
	"9": [["山东", "Shandong"], ["济南", "Jinan"], ["青岛", "Qingdao"], ["菏泽", "Heze"], ["济宁", "Jining"], ["莱芜", "Laiwu"], ["枣庄", "Zaozhuang"], ["临沂", "Linyi"], ["日照", "Rizhao"], ["淄博", "Zibo"], ["滨州", "Binzhou"], ["东营", "Dongying"], ["聊城", "Liaocheng"], ["德州", "Dezhou"], ["潍坊", "Weifang"], ["烟台", "Yantai"], ["威海", "Weihai"], ["泰安", "Taian"]], 
	"10": [["青海", "Qinghai"], ["西宁", "Xining"], ["海东", "Haidong"], ["海西", "Haixi"], ["海南", "Hainan"], ["海北", "Haibei"], ["玉树", "Yushu"], ["黄南", "Huangnan"], ["果洛", "Guoluo"]], 
	"11": [["宁夏", "Ningxia"], ["银川", "Yinchuan"], ["中卫", "Zhongwei"], ["吴忠", "Wuzhong"], ["固原", "Guyuan"], ["石嘴山", "Shizuishan"]], 
	"12": [["内蒙古", "Neimenggu"], ["呼和浩特", "Huhehaote"], ["乌兰察布", "Wulanchabu"], ["包头", "Baotou"], ["阿拉善", "Alashan"], ["鄂尔多斯", "Eerduosi"], ["乌海", "Wuhai"], ["锡林郭勒", "Xilinguole"], ["呼伦贝尔", "Hulunbeier"], ["赤峰", "Chifeng"], ["通辽", "Tongliao"], ["兴安", "Xingan"]], 
	"13": [["辽宁", "Liaoning"], ["沈阳", "Shenyang"], ["大连", "Dalian"], ["锦州", "Jinzhou"], ["辽阳", "Liaoyang"], ["本溪", "Benxi"], ["鞍山", "Anshan"], ["丹东", "Dandong"], ["营口", "Yingkou"], ["盘锦", "Panjin"], ["阜新", "Fuxin"], ["铁岭", "Tieling"], ["抚顺", "Fushun"], ["朝阳", "Zhaoyang"], ["葫芦岛", "Huludao"]], 
	"14": [["江西", "Jiangxi"], ["南昌", "Nanchang"], ["九江", "Jiujiang"], ["赣州", "Ganzhou"], ["吉安", "Jian"], ["抚州", "Fuzhou"], ["宜春", "Yichun"], ["新余", "Xinyu"], ["萍乡", "Pingxiang"], ["上饶", "Shangrao"], ["鹰潭", "Yingtan"], ["景德镇", "Jingdezhen"]], 
	"15": [["吉林", "Jilin"], ["长春", "Changchun"], ["吉林", "Jilin"], ["白山", "Baishan"], ["四平", "Siping"], ["松原", "Songyuan"], ["白城", "Baicheng"], ["通化", "Tonghua"], ["辽源", "Liaoyuan"], ["延边", "Yanbian"]], 
	"16": [["湖南", "Hunan"], ["长沙", "Changsha"], ["岳阳", "Yueyang"], ["衡阳", "Hengyang"], ["湘潭", "Xiangtan"], ["永州", "Yongzhou"], ["株洲", "Zhuzhou"], ["郴州", "Chenzhou"], ["邵阳", "Shaoyang"], ["怀化", "Huaihua"], ["娄底", "Loudi"], ["益阳", "Yiyang"], ["常德", "Changde"], ["张家界", "Zhangjiajie"], ["湘西", "Xiangxi"]], 
	"17": [["湖北", "Hubei"], ["武汉", "Wuhan"], ["襄阳", "Xiangyang"], ["荆门", "Jingmen"], ["荆州", "Jingzhou"], ["孝感", "Xiaogan"], ["黄冈", "Huanggang"], ["黄石", "Huangshi"], ["宜昌", "Yichang"], ["十堰", "Shiyan"], ["随州", "Suizhou"], ["鄂州", "Ezhou"], ["恩施", "Enshi"], ["省直辖", "Shengzhixia"]], 
	"18": [["黑龙江", "Heilongjiang"], ["哈尔滨", "Haerbin"], ["齐齐哈尔", "Qiqihaer"], ["大庆", "Daqing"], ["绥化", "Suihua"], ["黑河", "Heihe"], ["伊春", "Yichun"], ["鹤岗", "Hegang"], ["七台河", "Qitaihe"], ["牡丹江", "Mudanjiang"], ["鸡西", "Jixi"], ["双鸭山", "Shuangyashan"], ["佳木斯", "Jiamusi"], ["大兴安岭", "Daxinganling"]], 
	"19": [["河南", "Henan"], ["郑州", "Zhengzhou"], ["许昌", "Xuchang"], ["平顶山", "Pingdingshan"], ["开封", "Kaifeng"], ["商丘", "Shangqiu"], ["新乡", "Xinxiang"], ["焦作", "Jiaozuo"], ["洛阳", "Luoyang"], ["南阳", "Nanyang"], ["驻马店", "Zhumadian"], ["三门峡", "Sanmenxia"], ["漯河", "Tahe"], ["周口", "Zhoukou"], ["鹤壁", "Hebi"], ["安阳", "Anyang"], ["濮阳", "Puyang"], ["信阳", "Xinyang"]], 
	"20": [["北京", "Beijing"], ["北京", "Beijing"]], 
	"21": [["天津", "Tianjin"], ["天津", "Tianjin"]], 
	"22": [["海南", "Hainan"], ["海口", "Haikou"], ["三亚", "Sanya"]], 
	"23": [["贵州", "Guizhou"], ["贵阳", "Guiyang"], ["遵义", "Zunyi"], ["铜仁", "Tongren"], ["六盘水", "Liupanshui"], ["毕节", "Bijie"], ["安顺", "Anshun"], ["黔东南", "Qiandongnan"], ["黔南", "Qiannan"], ["黔西南", "Qianxinan"]], 
	"24": [["广西", "Guangxi"], ["南宁", "Nanning"], ["桂林", "Guilin"], ["柳州", "Liuzhou"], ["来宾", "Laibin"], ["河池", "Hechi"], ["白色", "Baise"], ["贺州", "Hezhou"], ["梧州", "Wuzhou"], ["钦州", "Qinzhou"], ["贵港", "Guigang"], ["防城港", "Fangchenggang"], ["北海", "Beihai"], ["玉林", "Yulin"], ["崇左", "Chongzuo"]], 
	"25": [["甘肃", "Gansu"], ["兰州", "Lanzhou"], ["白银", "Baiyin"], ["定西", "Dingxi"], ["天水", "Tianshui"], ["庆阳", "Qingyang"], ["平凉", "Pingliang"], ["陇南", "Longnan"], ["武威", "Wuwei"], ["金昌", "Jinchang"], ["张掖", "Zhangye"], ["酒泉", "Jiuquan"], ["嘉峪关", "Jiayuguan"], ["临夏", "Linxia"], ["甘南", "Gannan"]], 
	"26": [["福建", "Fujian"], ["福州", "Fuzhou"], ["厦门", "Shamen"], ["泉州", "Quanzhou"], ["龙岩", "Longyan"], ["莆田", "Futian"], ["三明", "Sanming"], ["宁德", "Ningde"], ["南平", "Nanping"], ["漳州", "Zhangzhou"]], 
	"27": [["澳门", "Aomen"], ["澳门", "Aomen"]], 
	"28": [["安徽", "Anhui"], ["合肥", "Hefei"], ["淮北", "Huaibei"], ["宿州", "Suzhou"], ["蚌埠", "Bangbu"], ["六安", "Liuan"], ["阜阳", "Fuyang"], ["亳州", "Bozhou"], ["芜湖", "Wuhu"], ["安庆", "Anqing"], ["宣城", "Xuancheng"], ["马鞍山", "Maanshan"], ["淮南", "Huainan"], ["铜陵", "Tongling"], ["池州", "Chizhou"], ["滁州", "Chuzhou"], ["黄山", "Huangshan"]], 
	"29": [["上海", "Shanghai"], ["上海", "Shanghai"]], 
	"30": [["重庆", "Chongqing"], ["重庆", "Chongqing"]], 
	"31": [["江苏", "Jiangsu"], ["南京", "Nanjing"], ["苏州", "Suzhou"], ["扬州", "Yangzhou"], ["无锡", "Wuxi"], ["镇江", "Zhenjiang"], ["常州", "Changzhou"], ["南通", "Nantong"], ["泰州", "Taizhou"], ["盐城", "Yancheng"], ["淮安", "Huaian"], ["宿迁", "Suqian"], ["徐州", "Xuzhou"], ["连云港", "Lianyungang"]], 
	"32": [["广东", "Guangdong"], ["广州", "Guangzhou"], ["深圳", "Shenzhen"], ["珠海", "Zhuhai"], ["中山", "Zhongshan"], ["佛山", "Foshan"], ["东莞", "Dongguan"], ["惠州", "Huizhou"], ["肇庆", "Zhaoqing"], ["云浮", "Yunfu"], ["茂名", "Maoming"], ["湛江", "Zhanjiang"], ["阳江", "Yangjiang"], ["江门", "Jiangmen"], ["清远", "Qingyuan"], ["韶关", "Shaoguan"], ["河源", "Heyuan"], ["梅州", "Meizhou"], ["汕尾", "Shanwei"], ["汕头", "Shantou"], ["揭阳", "Jieyang"], ["潮州", "Chaozhou"]], 
	"33": [["河北", "Hebei"], ["石家庄", "Shijiazhuang"], ["保定", "Baoding"], ["承德", "Chengde"], ["唐山", "Tangshan"], ["廊坊", "Langfang"], ["衡水", "Hengshui"], ["邢台", "Xingtai"], ["沧州", "Cangzhou"], ["邯郸", "Handan"], ["秦皇岛", "Qinhuangdao"], ["张家口", "Zhangjiakou"]]}
	
